version: "3.8"

services:
    app:
        image: node:15
        command: sh -c "npm install && npm start"
        ports:
            - 2999:2999
        working_dir: /app
        volumes:
            - ./:/app
